services:
  - type: web
    name: discord-ai-selfbot
    env: python
    plan: free
    buildCommand: pip install -r requirements-render.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DISCORD_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ERROR_WEBHOOK_URL
        sync: false
    autoDeploy: false